<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vinosenth" failures="1" tests="3" name="Test" time="8.48" errors="0" timestamp="2023-07-23T19:55:22 IST">
  <testcase classname="com.sdet.TC1_Login" name="logintest" time="8.408"/>
  <testcase classname="com.sdet.App_Test" name="logintest1" time="0.035">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at com.sdet.App_Test.logintest1(App_Test.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- logintest1 -->
  <testcase classname="com.sdet.App_Test" name="logintest2" time="0.001"/>
</testsuite> <!-- Test -->
